### ISSUE TITLE
Running the entire pipeline

### ISSUE THREAD

**Issue by Sahana-selvarathnam** [sbslee/pypgx#107]
Hi Steven,

I have a bam and vcf file of a sample and I want to run pypgx on this data for all genes and fetch all possible genotype and phenotype for the sample? 
Can you please explain the process of doing this?

**Comment by sbslee** [comment]
Hi @Sahana-selvarathnam,

This depends on the nature of your input data. Is it WGS or WES or targeted panel sequencing?

**Comment by Sahana-selvarathnam** [comment]
It is WGS data

**Comment by sbslee** [comment]
Then you should use the [pypgx run-ngs-pipeline](https://pypgx.readthedocs.io/en/latest/readme.html#ngs-pipeline) command. Below is an example command for CYP2D6 (which includes SV detection):

```
$ pypgx run-ngs-pipeline \
CYP2D6 \
grch37-CYP2D6-pipeline \
--variants grch37-variants.vcf.gz \
--depth-of-coverage grch37-depth-of-coverage.zip \
--control-statistics grch37-control-statistics-VDR.zip
```

You can create a for loop for studying multiple genes. Please visit the link to learn how to create the input files. Please let me know if you need further help.

**Comment by sbslee** [comment]
You can also find WGS tutorial [here](https://pypgx.readthedocs.io/en/latest/tutorials.html#get-rm-wgs-tutorial).

**Comment by Sahana-selvarathnam** [comment]
I have been trying to generate input file using the create-input-vcf option but it says fasta file is required which I don't have.

**Comment by sbslee** [comment]
Do you know which reference genome (hg19 vs. hg38) was used to create your BAM file?

**Comment by Sahana-selvarathnam** [comment]
hg19 was used. I have downloaded the genome.fa file from the link provided by you and generated the input vcf file but while running run-ngs-pipeline I am facing a file not found error. It says ###.bam.png file is not found in grch37-CYP2D6-pipeline folder. How should I generate the file?

**Comment by sbslee** [comment]
Please provide the exact command line you used and also the entire output including the error message.

**Comment by Sahana-selvarathnam** [comment]
pypgx run-ngs-pipeline CYP2D6 grch37-CYP2D6-pipeline/ --variants grch37-variants.vcf.gz --depth-of-coverage grch37-depth-of-coverage.zip --control-statistics grch37-control-statistics-VDR.zip
Saved VcfFrame[Imported] to: grch37-CYP2D6-pipeline//imported-variants.zip
Saved VcfFrame[Phased] to: grch37-CYP2D6-pipeline//phased-variants.zip
Saved VcfFrame[Consolidated] to: grch37-CYP2D6-pipeline//consolidated-variants.zip
Saved SampleTable[Alleles] to: grch37-CYP2D6-pipeline//alleles.zip
Traceback (most recent call last):
  File "/home/vijhayalakshmi/anaconda3/bin/pypgx", line 8, in <module>
    sys.exit(main())
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/pypgx/__main__.py", line 33, in main
    commands[args.command].main(args)
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/pypgx/cli/run_ngs_pipeline.py", line 159, in main
    pipeline.run_ngs_pipeline(
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/pypgx/api/pipeline.py", line 260, in run_ngs_pipeline
    plot.plot_vcf_allele_fraction(
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/pypgx/api/plot.py", line 409, in plot_vcf_allele_fraction
    fig.savefig(output)
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/matplotlib/figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/matplotlib/image.py", line 1616, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/vijhayalakshmi/anaconda3/lib/python3.9/site-packages/PIL/Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'grch37-CYP2D6-pipeline//allele-fraction-profile//home/vijhayalakshmi/PGx/55001705013845.bam.png'

**Comment by sbslee** [comment]
The error was caused because your BAM file is missing the sample name field (`SM`) and therefore in the VCF file, the entire path to your BAM file was set as the sample name (i.e. `/home/vijhayalakshmi/PGx/55001705013845.bam`). To fix this issue, you need to provide a sensible sample name to your BAM. See my previous reply in #96 where other users had the exactly same issue:

Another user recently raised an issue (#105) that I think is related to your case:

> @muhligs,
> 
> Thanks for sending the header. As you can see, there is no read group tag (i.e. a line that starts with `@RG`) in the header, which should contain the sample name field (`SM`). You usually specify read group during the alignment step (when running `bwa mem` in your case). Additionally, I checked your attached files and, as speculated, the original BAM path was set as sample name.
> 
> Please add read group to your BAM to give a proper sample name and then run PyPGx on the new BAM. You can find more examples of read group in the Internet, but below is one example:
> 
> ```
> @RG ID:H0164.2  PL:illumina PU:H0164ALXX140820.2    LB:Solexa-272222    PI:0    DT:2014-08-20T00:00:00-0400 SM:NA12878  CN:BI
> ```


> FYI, you can easily add read group to existing BAM using existing tools like [samtools addreplacerg](http://www.htslib.org/doc/samtools-addreplacerg.html).

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
