### ISSUE TITLE
All G6PD phenotypes are "Indeterminate", even when it seems that some should not be based on the diplotype? 

### ISSUE THREAD

**Issue by brettva** [sbslee/pypgx#119]
Hi Steven,

Thank you for developing pypgx we use it quite a bit at our biobank . I am working on calling G6PD phenotypes for our participants.

I noticed all participants seem to be called "Indeterminate" for G6PD from pypgx, but just spot checking a few of the diplotypes from pypgx with [diplotype to phenotype tables from PharmGKB](https://files.cpicpgx.org/data/report/current/diplotype_phenotype/G6PD_Diplotype_Phenotype_Table.xlsx) it does not seem to line up.

For example, our two most common non-homozygous reference diplotypes are:

A/B, which should be "Normal Risk" based on PharmGKB but is "Indeterminate" from pypgx
A- 202A_376G/B (reference), which should be "G6PD Variable" based on PharmGKB but is "Indeterminate" from pypgx

I am assuming that it is due to lack of CPIC support for this gene:

https://pypgx.readthedocs.io/en/latest/genes.html?highlight=cpic

I know G6PD is troublesome due to being on X, so I wondering if that affected the logic to default to "Indeterminate" instead of mapping to available phenotypes? 

Please let me know, thank you!

**Comment by sbslee** [comment]
@brettva,

Happy New Year! Thanks for your continued interest in PyPGx. And thanks for introducing me to G6PD's diplotype-phenotype table from PharmGKB. I confirm that the same table is being offered by [CPIC](https://cpicpgx.org/guidelines/cpic-guideline-for-g6pd/) as well. This will certainly help me add phenotype data for G6PD to PyPGx. I will make this update ASAP.

**Comment by brettva** [comment]
@sbslee Thank you so much!

**Comment by sbslee** [comment]
@brettva,

I've got some good news! I finished adding G6PD phenotype data to the `0.24.0` branch. My testing indicates that everything works as expected, but I'd greatly appreciate if you could test it out too. For example, here are the G6PD results from the [GeT-RM WGS tutorial](https://pypgx.readthedocs.io/en/latest/tutorials.html#get-rm-wgs-tutorial):

[results.zip](https://github.com/sbslee/pypgx/files/13852509/results.zip)

```
(fuc) sbslee@Seung-beens-MacBook-Air Desktop % cd getrm-wgs-tutorial 
(fuc) sbslee@Seung-beens-MacBook-Air getrm-wgs-tutorial % pypgx run-ngs-pipeline \
G6PD \
grch37-G6PD-pipeline \
--variants grch37-variants.vcf.gz \
--depth-of-coverage grch37-depth-of-coverage.zip \
--control-statistics grch37-control-statistics-VDR.zip
Saved VcfFrame[Imported] to: grch37-G6PD-pipeline/imported-variants.zip
Saved VcfFrame[Phased] to: grch37-G6PD-pipeline/phased-variants.zip
Saved VcfFrame[Consolidated] to: grch37-G6PD-pipeline/consolidated-variants.zip
Saved SampleTable[Alleles] to: grch37-G6PD-pipeline/alleles.zip
Saved CovFrame[ReadDepth] to: grch37-G6PD-pipeline/read-depth.zip
Saved CovFrame[CopyNumber] to: grch37-G6PD-pipeline/copy-number.zip
/Users/sbslee/opt/anaconda3/envs/fuc/lib/python3.10/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 0.24.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sbslee/opt/anaconda3/envs/fuc/lib/python3.10/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator LabelBinarizer from version 0.24.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sbslee/opt/anaconda3/envs/fuc/lib/python3.10/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator OneVsRestClassifier from version 0.24.2 when using version 1.3.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Saved SampleTable[CNVCalls] to: grch37-G6PD-pipeline/cnv-calls.zip
Saved SampleTable[Genotypes] to: grch37-G6PD-pipeline/genotypes.zip
Saved SampleTable[Phenotypes] to: grch37-G6PD-pipeline/phenotypes.zip
Saved SampleTable[Results] to: grch37-G6PD-pipeline/results.zip
(fuc) sbslee@Seung-beens-MacBook-Air getrm-wgs-tutorial % pypgx print-data grch37-G6PD-pipeline/results.zip | head
	Genotype	Phenotype	Haplotype1	Haplotype2	AlternativePhase	VariantData	CNV
HG00589_PyPGx	MALE/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Male
NA07019_PyPGx	B (reference)/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Female
NA10851_PyPGx	MALE/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Male
NA18484_PyPGx	A- 202A_376G/A- 202A_376G	G6PD Deficient	A- 202A_376G;	A- 202A_376G;	;	A- 202A_376G:X-153764217-C-T,X-153763492-T-C:0.97,1.0;	Female
NA12006_PyPGx	B (reference)/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Female
HG00436_PyPGx	MALE/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Male
NA19213_PyPGx	MALE/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Male
NA19207_PyPGx	MALE/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Male
NA07029_PyPGx	MALE/B (reference)	G6PD Normal	B (reference);	B (reference);	;	B (reference):default;	Male
(fuc) sbslee@Seung-beens-MacBook-Air getrm-wgs-tutorial % 
```

**Comment by brettva** [comment]
@sbslee Thank you so much we will have a look!

**Comment by sbslee** [comment]
Will close this as it's completed.

**Comment by brettva** [comment]
Thanks again, this seems to be working as expected but I have a clarifying question.

 We are using genotypes from [TOPMed imputation](https://imputation.biodatacatalyst.nhlbi.nih.gov/#!) which codes diplotypes for both males are females on X. 

For example if a male has one copy of the alternate allele for rs1050828, it would be coded in the VCF from TOPMed as  GT=1|1 instead of GT=1 

I am using this command:

`pypgx run-chip-pipeline --assembly GRCh38 G6PD {output} {topmed_vcf} `

If try:

`pypgx print-data results.zip | head`

my CNV column is blank. I am guess you use the depth of coverage to infer copy number/sex.

For association tests, I think some extra work will have to be done on my end wrt to allele counts between males and females, but for now I just want to summarize G6PD phenotype frequency among my cohort. 

I am thinking for the phenotype frequency purpose it does not matter if both males and females are treated the same (as in both have diplotypes as input). I checked the results from PyPGx and as expected only females give heterozygous genotype and as expected males are G6PD deficient much more often than females. 

Are my assumptions right, or is this off somewhere? Please let me know, thank you.

**Comment by sbslee** [comment]
@brettva,

> Thanks again, this seems to be working as expected

Thanks for confirming that the new G6PD phenotype calling functionality is working as expected!

> my CNV column is blank. I am guess you use the depth of coverage to infer copy number/sex.

Yes, PyPGx uses CNV detection as a way to determine the sex of a sample.

> I am thinking for the phenotype frequency purpose it does not matter if both males and females are treated the same (as in both have diplotypes as input). I checked the results from PyPGx and as expected only females give heterozygous genotype and as expected males are G6PD deficient much more often than females.

In order to ensure that both males and females are treated uniformly in terms of phenotypes, please refer to the diplotype-to-phenotype mapping [table](https://github.com/sbslee/pypgx/blob/0.24.0-dev/pypgx/api/data/diplotype-table.csv) used by PyPGx. Upon a preliminary review of this table, I tend to agree with you, but there might be edge cases that warrant more in-depth examination.

**Comment by sbslee** [comment]
@brettva,

Alternatively, I've got an idea! If you already know the sex of the samples, you could manually create a `SampleTable[CNVCalls]` file and use it to call final diplotypes. The file should look like this:

```
(fuc) sbslee@Seung-beens-MacBook-Air getrm-wgs-tutorial % pypgx print-data grch37-G6PD-pipeline/cnv-calls.zip | head
	CNV
HG00589_PyPGx	Male
NA07019_PyPGx	Female
NA10851_PyPGx	Male
NA18484_PyPGx	Female
NA12006_PyPGx	Female
HG00436_PyPGx	Male
NA19213_PyPGx	Male
NA19207_PyPGx	Male
NA07029_PyPGx	Male
```

I'm attaching an example:

[grch37-G6PD-pipeline.zip](https://github.com/sbslee/pypgx/files/14215865/grch37-G6PD-pipeline.zip)

**Comment by brettva** [comment]
@sbslee good idea, I also checked to ensure that the phenotypes for haploid males and homozygous females were all the same and they are!
