### ISSUE TITLE
Long-Read Pipeline - unphased sites in VCF using WhatsHap

### ISSUE THREAD

**Issue by sumudu-rangika** [sbslee/pypgx#120]
Hi Steven,

A blessed 2024 !

I have two queries.
1) I am analyzing WGS Oxford Nanopore data. The per-sample VCFs were phased using WhatsHap tool. I noticed that nearly 33% of the sites in my interested PGx regions are not phased. Also, by using the Clair3 tool with --enable-phased option resulted ~41% variants unphased in the VCFs. 

Appreciate your thoughts on how to handle unphased sites in VCF when using these as input to PyPGx long read pipeline.

 2) Does the PyPGx slice-bam option include control regions? The PyPGx gene-table has RYR1 but no coordinates mentioned for VDR or EGFR regions, which are usually used as control genes. 

Thanks 
Best
Sumudu

**Comment by sbslee** [comment]
@sumudu-rangika,

Happy New Year! I will get back to you on the first question later.

As for the second question, yes, `slice-bam` will return reads for control regions as well. The command includes all the regions used by PyPGx:

[gene-table.csv](https://github.com/sbslee/pypgx/files/13842521/gene-table.csv)

```
(fuc) sbslee@Seung-beens-MacBook-Air pypgx % pypgx create-regions-bed
1	201005639	201084694	CACNA1S
1	60355979	60395470	CYP2J2
1	47391859	47410148	CYP4A11
1	47600112	47618399	CYP4A22
1	47261669	47288021	CYP4B1
1	97540298	98389615	DPYD
1	169478188	169558719	F5
1	110227417	110239367	GSTM1
1	11842779	11869021	MTHFR
2	38291745	38306323	CYP1B1
2	234662918	234687945	UGT1A1
2	234624437	234684945	UGT1A4
3	121610170	121666034	SLC15A2
3	14183646	14223172	XPC
4	89008420	89082791	ABCG2
4	69959191	69981705	UGT2B7
4	69506314	69542494	UGT2B15
4	69399901	69437245	UGT2B17
6	160627786	160689853	SLC22A2
6	18125541	18158400	TPMT
7	87130178	87345639	ABCB1
7	117117016	117311719	CFTR
7	1019834	1032276	CYP2W1
7	99351582	99384811	CYP3A4
7	99242811	99280649	CYP3A5
7	99299659	99335823	CYP3A7
7	99422635	99466727	CYP3A43
7	55083713	55278773	EGFR
7	75541419	75619173	POR
7	139525951	139723125	TBXAS1
8	18064617	18084198	NAT1
8	18245791	18261728	NAT2
10	96793528	96832254	CYP2C8
10	96695414	96752148	CYP2C9
10	96519437	96615962	CYP2C19
10	135330866	135362620	CYP2E1
10	104587287	104600170	CYP17A1
10	94830646	94840641	CYP26A1
11	14896554	14916751	CYP2R1
11	67348065	67357124	GSTP1
11	74859151	74920594	SLCO2B1
12	21281127	21395730	SLCO1B1
12	20960637	21072845	SLCO1B3
12	48232319	48301814	VDR
13	48608702	48624364	NUDT15
15	75008882	75020951	CYP1A1
15	75038183	75051941	CYP1A2
15	51497253	51633795	CYP19A1
16	28601907	28636365	SULT1A1
16	31099162	31109320	VKORC1
19	41339442	41396352	CYP2A6
19	41381343	41388657	CYP2A7
19	41574355	41622100	CYP2A13
19	41427203	41534301	CYP2B6
19	41430169	41456565	CYP2B7
19	41617336	41637286	CYP2F1
19	41696111	41716444	CYP2S1
19	15973833	16023930	CYP4F2
19	39731245	39744165	IFNL3
19	38921339	39081204	RYR1
20	48117410	48187674	PTGIS
22	19917359	19962473	COMT
22	42512500	42551883	CYP2D6
22	42536213	42540576	CYP2D7
22	24373132	24387311	GSTT1
X	153756604	153778233	G6PD
```

**Comment by sumudu-rangika** [comment]
Thanks a lot !

Best
Sumudu

**Comment by sbslee** [comment]
Regarding your first question, I'm somewhat surprised to hear that a significant fraction of the variants remained unphased despite using long-read data. Personally, I don't have much experience with long reads, but I would assume the phasing rate to be much higher.

Is your WGS data low-pass (low depth of coverage)?

What is the average phasing rate for the entire WGS?

Did you check to see which PGx genes or regions exhibited a lower phasing rate? 

You could still run the `pypgx run-ngs-pipeline` command with your partially phased VCF file. In this scenario, PyPGx will simply disregard the initial phasing and attempt re-phasing using statistical methods. However, this means losing valuable phase information obtained from the long-read data.

**Comment by sumudu-rangika** [comment]
Hi Steven,

Thanks for the reply. This is my first time working with Long Reads and I am still trying to understand the data. 

The BAMs I work in this trial has average coverage 35x-51x. The particular BAM I'm trying to phase has 44x average coverage.
For the entire WGS average phasing using whatshap is 62% and Clair3 with enable phasing is 53%. 

Generally genes in chromosomes 1,7,10,12 and 19 has lower phasing. E.g., DPYD, CACNA1S, SLCO1B1, CYP4F2 etc.

I also noticed that some unphased regions have long stretches of homozygous alternate variants. But not all of them.

I can share with you the extracted phased VCF via email and also the corresponding BAM file for the extracted PGx regions and appreciate if you can have a look at it. 

Another problem is that, I tried to generate a multi-sample VCF from phased per-sample VCF files to input into pypgx run-long-read-pipeline. I used the bcftools command as usual to merge the VCFs (`bcftools merge --threads ${nthreads} -m none -Oz -o $output/all_whatshap_phased.vcf.gz -l $output/phased_list_vcfs.txt`). But I keep getting an error which I couldn't figure out. when I run individual VCF files the pipeline runs without errors. The error is:

> Traceback (most recent call last):
>   File "/home/n11009985/.local/bin/pypgx", line 8, in <module>
>     sys.exit(main())
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pypgx/__main__.py", line 33, in main
>     commands[args.command].main(args)
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pypgx/cli/run_long_read_pipeline.py", line 76, in main
>     pipeline.run_long_read_pipeline(
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pypgx/api/pipeline.py", line 118, in run_long_read_pipeline
>     consolidated_variants = utils.import_variants(gene, variants,
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pypgx/api/utils.py", line 1065, in import_variants
>     vf = _phase_extension(vf, gene, assembly)
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pypgx/api/utils.py", line 139, in _phase_extension
>     return pyvcf.VcfFrame([], vf.df.apply(one_row, axis=1))
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 10034, in apply
>     return op.apply().__finalize__(self, method="apply")
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pandas/core/apply.py", line 837, in apply
>     return self.apply_standard()
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pandas/core/apply.py", line 965, in apply_standard
>     results, res_index = self.apply_series_generator()
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
>     results[i] = self.func(v, *self.args, **self.kwargs)
>   File "/home/n11009985/.local/lib/python3.9/site-packages/pypgx/api/utils.py", line 85, in one_row
>     alt_allele = r.ALT.split(',')[int(gt[i]) - 1]
> ValueError: invalid literal for int() with base 10: '1|0'
 
Best
Sumudu

**Comment by sbslee** [comment]
@sumudu-rangika,

> The BAMs I work in this trial has average coverage 35x-51x. The particular BAM I'm trying to phase has 44x average coverage.

Interesting, so the coverage is not an issue.

> For the entire WGS average phasing using whatshap is 62% and Clair3 with enable phasing is 53%.

I'd be curious if 50-60% is the expected phasing rate for ONT WGS data.

> I can share with you the extracted phased VCF via email and also the corresponding BAM file for the extracted PGx regions and appreciate if you can have a look at it.

Sure, please send them to me over. I'd be happy to take a look at them.

> Another problem is that, I tried to generate a multi-sample VCF from phased per-sample VCF files to input into pypgx run-long-read-pipeline.

Is there any particular reason you want to input a multi-sample VCF instead of single-sample VCF?

> But I keep getting an error which I couldn't figure out. when I run individual VCF files the pipeline runs without errors. The error is:

Please send me both the multi-sample VCF and single-sample VCFs. I will take a look.

**Comment by sumudu-rangika** [comment]
Thanks for the reply. 

After examining the VCF, it appears that the unphased heterozygous variants are multi-allelic sites. Whenever a split multi-allelic site is encountered, whatshap phases only one variant at the same position, leaving the other variant unphased. If I use a VCF without splitting, multi-allelic sites are not phased at all. 

splitting using BCFtools for e.g. 
1 102345 A G,C

1 102345 A G 0/1
1 102345 A C 1/0

After phasing some variants appear as 
1 102345 A G 0/1
1 102345 A C 0|1

I wondering if I should edit the phasing and genotype arrangement as 1 102345 A G 1|0 ? Because whatshap can't handle it. 

The error in the multi-allelic VCF input to PyPGx was solved after replacing the unphased sites ('/') to ('|'), and the long-read pipeline worked. 

Best
Sumudu

**Comment by sbslee** [comment]
@sumudu-rangika,

Interesting! Although I don't understand why WhatsHap can't handle multiallelic sites, if you can manually fix those incidents, I don't see any issues with that.

**Comment by sumudu-rangika** [comment]
'whatshap phase' doesn't handle multi allelic sites. But I saw a recent edit 'whatshap polyphase' could probably handle these sites https://github.com/whatshap/whatshap/pull/450. But haven't tried yet. I wrote a python script to edit the multi allelic sites. I will share my phased and phase-edited files for you to have  a look. Thank you !

Best
Sumudu

**Comment by sbslee** [comment]
I will close this issue for now as it's more related to WhatsHap than it is to PyPGx.
