### ISSUE TITLE
Recommendations new version and custom recommendations

### ISSUE THREAD

**Issue by Bioinf-usr** [sbslee/pypgx#124]
Hi Steven,

Are you planning to update the recommendation sheet by any chance? Also, if we want to use our custom recommendations is it possible?

I meant this table: https://github.com/sbslee/pypgx/blob/master/pypgx/api/data/recommendation-table.csv

Thank you.

**Comment by sbslee** [comment]
@Bioinf-usr,

If there has been an update to the recommendation table, I'd be more than happy to update it! Could you kindly point me to webpages (e.g. CPIC, PharmVar) where the update is described?

Also, my goal of developing PyPGx always has been to make it a community effort. If you'd like, you're more than welcome to create a pull request with the update.

As for using your own custom recommendation table, sure, you could easily change the recommendation-table.csv file and PyPGx will simply obey what it sees there. If you are simply making the table up-to-date with the latest CPIC version, for example, however, I would strongly argue that it might be just better to make the update as an official PyPGx version.

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
