### ISSUE TITLE
v 0.24.0 copy-number-profile issue for G6PD and CYP2D6

### ISSUE THREAD

**Issue by ChristineHOconnor** [sbslee/pypgx#131]
I am using PyPGx v0.24.0 to run run-ngs-pipeline on a set of 18 samples. I start with fastq files and use PyPGx internal BAM and VCF calling. Everything runs, but I've noticed that all samples are called as 'Female' in the G6PD CNV column, even though all samples are not female. I have looked at the copy-number-profile plot for all 18 samples for G6PD and I saw that every sample has a straight line at 2 along the Y axis, not a line the 'bounces' up and down, like in the tutorial sample file. I have not looked at every BAM file in IGV, but the ones I looked at there was good coverage over G6PD and the couple of VCF files I looked at had a few variants called over G6PD coordinates on the X chromosome.

I am also having a similar issue with CYP2D6 CNV calling. One sample is supposed to have a CYP2D6 deletion, but it shows up as 'Normal' in the results text file for CYP2D6. The copy-number-profile plot has a straight line at 2 along the Y axis, but the allele-fraction-profile plot does not show any variants called over CYP2D6 coordinates, which is matched by no variants called over that region in the VCF file. Another sample that is supposed to by CYP2D6 normal shows some alleles in the allele-fraction-profile graph and the VCF file. The CYP2D6 normal sample has variants called in the VCF file and output in the allele-fraction-profile plot. 

I am using a custom BED file and aligning samples to GRCh38. 

Is there something else I can check with my data, besides looking at BAM coverage and variant calls in the VCF to QC my data, or might this be an issue with the CNV calling part of the pipeline?

**Comment by sbslee** [comment]
Hi @ChristineHOconnor,

Could you please send me the input files (i.e., --variants, --depth-of-coverage, --control-statistics) and the exact command line you used to replicate the error at sbstevenlee@gmail.com? It is difficult to solve the problem without seeing the data.

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
