### ISSUE TITLE
Incorrect phenotype prediction for wild type diplotypes in CYP1A1, CYP2A6, CYP2C8 and CYP4F2

### ISSUE THREAD

**Issue by Svenvdm** [sbslee/pypgx#137]
Hi Steven

When using the predict.phenotype function of pypgx v.0.25.0, it often returns Indeterminate phenotypes for wild type diplotypes(*1/*1), while the *1 is defined as a "Normal Function" allele in the pypgx allele table. Examples I have found are: CYP1A1, CYP2A6, CYP2C8 and CYP4F2. Even if there is no phenotype table available for these genes, shouldn't wild types be asssigned a normal function by default?

eg.
`pypgx.predict_phenotype("CYP1A1", "*1", "*1")` returns "Indeterminate"

Kind regards
Sven

**Comment by sbslee** [comment]
Hi @Svenvdm,

Thanks for the question. While it is true that the `CYP1A1*1` allele is defined to have `Normal Function`:

https://github.com/sbslee/pypgx/blob/7bec840a03b54556feac9fb80351875c3a48d669/pypgx/api/data/allele-table.csv#L99

The CYP1A1 gene itself does not support phenotype prediction (e.g., compare the [CYP1A1](https://pypgx.readthedocs.io/en/latest/genes.html#cyp1a1) vs. [CYP2D6](https://pypgx.readthedocs.io/en/latest/genes.html#phenotype-summary-for-cyp2d6) sections of the Genes page of the Read the Docs). As of today, there are 17 genes that support phenotype prediction based on the CPIC guidelines. You can read more on the [Phenotype prediction](https://pypgx.readthedocs.io/en/latest/readme.html#phenotype-prediction) section of the Read the Docs.

Hope this helps.

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
