### ISSUE TITLE
Working with Large BAM files

### ISSUE THREAD

**Issue by abheda24** [sbslee/pypgx#141]
I am trying to test pypgx on 1000 genomes database, the CRAM file is around 13 GB and after converting to BAM is around 34 GB. I am trying to use create-input-vcf to generate a vcf file the files are sorted and indexed. I dont know what the issue is but i was only able to generate a file which was just 370K which is very low and the process was completed in 12 secs. I installed via pip and also downloaded the pypgx bundle, Could you please guide me?

**Comment by sbslee** [comment]
Hi @abheda24,

1. Is the CRAM file you used a high-coverage (e.g., 30x) WGS sample?
2. When running the CLI, did you make sure that the genome build is correct (GRCh37 vs. GRCh38)?
3. What's the PyPGx version are you using?
4. I recently published a [paper](https://www.nature.com/articles/s41598-024-73748-3) where I applied PyPGx to the entire 2,504 samples from 1KGP.

**Comment by abheda24** [comment]
1.Yes, Its an high coverage WGS sample (30x) from the 1000 genomes database around 13 GB.
2.Yes, i used GRCh38 which is correct.
3.The version i am using is 0.25.0
4.I will check the implementation, thanks .

**Comment by sbslee** [comment]
Can you share the exact CLI you used for creating the VCF and also the exact terminal output?

**Comment by abheda24** [comment]
pypgx create-input-vcf \
  ~/pgx_pipeline/input/NA06991-variants.vcf.gz \
  ~/pgx_pipeline/input/GRCh38_full_analysis_set_plus_decoy_hla.fa \
  ~/pgx_pipeline/input/NA06991.cram \
  --assembly GRCh38
  
  The output returned the files with 369KB and process was completed in 0.12 minutes

**Comment by sbslee** [comment]
Could you send me the output VCF?

**Comment by abheda24** [comment]
[NA06991-variants.vcf.gz](https://github.com/user-attachments/files/17551514/NA06991-variants.vcf.gz)

**Comment by sbslee** [comment]
Thanks. The VCF file looks fine to me. Have you tried running PyPGx on it?

**Comment by abheda24** [comment]
I will run the Ngs pipeline and let you know, you can close the issue. Thanks for your response
