### ISSUE TITLE
Stuck with the inputs

### ISSUE THREAD

**Issue by rajdbs32** [sbslee/pypgx#143]
Request: Help with Obtaining STAR Alleles from VCF Files (Illumina Short Read Sequencing, Dragen Variant Caller)
Hi,

I’m looking to get STAR alleles for a set of VCF files generated from Illumina short-read sequencing using the Dragen platform (variant caller). The VCF files have been obtained from sequencing, and I need to identify the corresponding STAR alleles, typically used in pharmacogenomics or for specific gene variants like CYP2D6.

Could you please help me with the following:

**Verifying VCF files:**
Are there any specific steps or checks I should perform to ensure my VCF files are correctly formatted for STAR allele identification? The files are from Dragen, so they should already have the standard variant calling format.

**Comment by rajdbs32** [comment]
Hi Dr. Lee,

**UPDATE:** I ran the following command using the pypgx tool to analyze CYP2D6 variants for a single sample:

pypgx run-ngs-pipeline CYP2D6 CYP2D6-pipeline --assembly GRCh38 --variants sample1.vcf.gz --platform Targeted
This successfully produced results for the sample. However, I now have a cohort of 2000 WES samples and need to run the same analysis across all of them.

Merging these 2000 VCF files will likely take days, and I’m looking for a more efficient way to carry out this analysis at scale. Can you suggest a strategy or workflow to process these files more quickly?

**Comment by sbslee** [comment]
Hi @rajdbs32,

Thanks for your interest in using PyPGx!

> Merging these 2000 VCF files will likely take days, and I’m looking for a more efficient way to carry out this analysis at scale. Can you suggest a strategy or workflow to process these files more quickly?

Please take a look at #108. Honestly, 2,000 samples is not that many ;) If you really want to speed things up, I would suggest you look into parallel computing. Basically, you could divide your samples into 10 batches, each with 100 samples, and then fire up 10 separate instances in AWS or Google Cloud. Also, please note that you do NOT need to merge 2,000 VCF files into one.

**Comment by rajdbs32** [comment]
Thank you, Dr. Lee. I have tried what you suggested and the tool works great.
