### ISSUE TITLE
How to perform single sample SV calling?

### ISSUE THREAD

**Issue by toddknutson** [sbslee/pypgx#145]
Hi Steven,

Thanks so much for developing PyPGx! We’ve enjoyed using your tool for the past year or longer!

My coworker submitted a question (https://github.com/sbslee/pypgx/issues/131) to your GitHub issues page in May. We are finally (my fault) getting back into this project and would like a little guidance. Instead of directly addressing her question above, I wanted to ask a broader question that might help us understand PyPGx better.

- We are trying to use PyPGx to process batches of Illumina targeted capture data (targeting multiple PGx related genes) and have exon level baits for these genes.
- We have also tiled our probes across the entire CYP2D6 and CYP2D7 region (but did not tile across any other genes known to have SV).
- Ideally, we would like to call star alleles on a per-sample basis (where the calls are dependent of the set of samples sequenced in any particular batch).
- Our approach was to process each individual sample, in isolation: (1) map reads, (2) use “create-input-vcf”, (3) “prepare-depth-of-coverage”, (4) “compute-control-statistics”, then (5) “run-ngs-pipeline”.
- We noticed that our CYP2D6 SV calls were problematic (the profile plots looked flat) — prompting us to ask the question above via GitHub.

This leads me to our main question: **Can PyPGx be used in a single-sample mode for star allele calling (SNV and SV)?** Or, are we required to process multiple samples together (generating a multi-sample VCF, multi-sample CovFrame[DepthOfCoverage], and multi-sample SampleTable[Statistics] tables)?

We’d be happy to share more info/code/commands if necessary. 

Thanks again!!
Todd

**Comment by sbslee** [comment]
Thank you for reaching out. PyPGx does support targeted sequencing data, but it requires more attention than whole genome sequencing data, especially if your goal is to perform structural variation (SV) detection:

1. If you are interested in performing SV detection, PyPGx requires read-depth data from multiple samples to perform intersample normalization. This process helps PyPGx establish a baseline by identifying what normal samples without SV look like in terms of read depth. If SV detection is not your focus, intersample normalization and copy number analysis are not necessary.

2. A common use case for targeted sequencing is clinical PGx implementation, where the analysis often involves a single sample. To achieve this, you need to generate sequencing data for control samples (using the same targeted capture) only once. You can then analyze your target sample alongside these control samples. Control samples refer to those without SV in the target gene of interest (e.g., CYP2D6). Coriell samples from the 1000 Genomes Project are often suitable for this purpose. For more details, please refer to the following [discussion](https://github.com/sbslee/pypgx/discussions/70).

Please let me know if you have any additional questions.
