### ISSUE TITLE
Phenotype -  CYP2C9, diplotype *2/*3 

### ISSUE THREAD

**Issue by ankita86** [sbslee/pypgx#18]
Hi Steven,
According to CPIC guidelines, diplotype *2/*3 (CYP2C9)  should be assigned poor_metabolizer instead of intermediate metabolizer.

**Comment by sbslee** [comment]
Hi @ankita86, I'm sorry it took a while to get back to you. I finally updated the `phenotyper()` method for CYP2C9 as you can see below:

```
from pypgx.phenotyper import phenotyper
print(phenotyper("cyp2c9", "*2", "*3"))
``` 

Which gives:

```
poor_metabolizer
```

This change has been made in the `0.3.0-dev` branch if you want to use the updated version of pypgx.

**Comment by sbslee** [comment]
Please feel free to let me know if you have any questions.
