### ISSUE TITLE
Speeding up VCF loading for large files

### ISSUE THREAD

**Issue by sbslee** [sbslee/pypgx#34]
I found that the current method for loading and processing VCF files is quite memory-demanding and time-consuming, especially for cohort WGS. I'm thinking about using cyvcf for the region slicing and then load the data into pandas Dataframe, do you think it's appropriate for Pypgx?

About CNV, currently I cannot open the CNV definition files in `pypgx/pypgx/api/cnv/GRCh38` because of the *.sav extension.

_Originally posted by @NTNguyen13 in https://github.com/sbslee/pypgx/issues/32#issuecomment-986598380_

**Comment by sbslee** [comment]
> 2\. I'm aware the `api.utils.import_variants` method is slow for large VCF files. Under the hood, it uses the `pyvcf.VcfFrame.from_file` method from the`fuc` package (it's also written by me). I recently updated the `pyvcf.VcfFrame.from_file` [method](https://sbslee-fuc.readthedocs.io/en/latest/api.html?highlight=VcfFrame.from_file#fuc.api.pyvcf.VcfFrame.from_file) to use random access to speed up VCF loading for specified region (via the `pysam` package). So I will update `api.utils.import_variants` to use this feature of `pyvcf.VcfFrame.from_file`. It should solve the VCF loading issue for large files.

**Comment by sbslee** [comment]
@NTNguyen13,

`run-ngs-pipeline` should now load large VCF files much faster. Please let me know if you run into any issues. Please don't forget to use the development branch of the `fuc` package when you do your own testing.

**Comment by NTNguyen13** [comment]
Hi, I will try it ASAP.

**Comment by sbslee** [comment]
@NTNguyen13, did you have a chance to test this new feature?

**Comment by NTNguyen13** [comment]
Hi, sorry for taking so long for this. Our server is currently experience some problem with the proxy, so I have to download some data to my local computer to test the new feature. It works well, the step `import variant` is super fast, and it creates a archive with Semantic file of ConsolidatedVcf, and ready for the next step.

Thank you very much.

**Comment by sbslee** [comment]
Thanks for letting me know! Closing this.
