### ISSUE TITLE
Citing PyPGx

### ISSUE THREAD

**Issue by NTNguyen13** [sbslee/pypgx#44]
Hi, I'm currently writing a manuscript related to Vietnamese PGx landscape. In that study, for generating star allele genotype and phenotype, I formerly used Stargazer, but now I'm using PyPGx, and the final manuscript is expected to use results from PyPGx too.

I would like to cite PyPGx, however I don't find the citation information anywhere, so I seek your advice on this one.

Thank you.

**Comment by sbslee** [comment]
@NTNguyen13,

Congratulations on your manuscript, and thanks for asking about citation! At this point, there are no publications describing PyPGx, so I think you probably want to just cite this repository (https://github.com/sbslee/pypgx). Please don't forget to include the version number.

Just out of curiosity, and it's totally understandable if you can't answer these questions now, how many individuals do you have for this paper and which sequencing platform did you use to sequence their DNA (e.g. WGS, targeted sequencing, WES)? Did you by any chance encounter any novel structural variants that were not properly detected by PyPGx?

**Comment by NTNguyen13** [comment]
Thanks!

We have roughly 1000 individuals enrolled in this study. For SV, we are constructing new pipelines, so I will share any updates with you as soon as possible.

You can take a look in [here](https://genome.vinbigdata.org/pgx_alleles), this is the old results that I used stargazer, I will update it to PyPGx soon. We planned to have this data portal open for researchers :)

**Comment by sbslee** [comment]
Thanks for sharing the information. That's awesome, and what a neat website you got there! Great job. Hope your paper gets published soon :) Best of luck.

**Comment by sbslee** [comment]
@NTNguyen13,

I know it's been a while, but I just wanted to let you know that PyPGx now has a citation!

Lee et al., 2022. [ClinPharmSeq: A targeted sequencing panel for clinical pharmacogenetics implementation](https://doi.org/10.1371/journal.pone.0272129). PLOS ONE.

For more information, please visit the CITATION section in the `0.18.0-dev` [docs](https://pypgx.readthedocs.io/en/0.18.0-dev/readme.html#citation).

Cheers

**Comment by NTNguyen13** [comment]
Congratulation regarding your publication! I'm grateful that HLA genes are included on that list. However, I see that the HLA typing is not included in the manuscript yet, as well as in Pypgx. If possible, I want to try to do some HLA typing on the ClinPharmSeq BAM files using third-party software and compare the result with truth set.
And my last question: Is ClinPharmSeq panel commercialized yet?
