### ISSUE TITLE
Add the ABCG2 gene to PyPGx

### ISSUE THREAD

**Issue by sbslee** [sbslee/pypgx#49]
A new CPIC [guideline](https://cpicpgx.org/guidelines/cpic-guideline-for-statins/) involving ABCG2 has been recently released.

**Comment by roman-tremmel** [comment]
Although the gene is listed on https://pypgx.readthedocs.io/en/latest/genes.html, the variant file is missing in the latest bundle. 
In addition the variant files of GSTT1 and UGT2B17 are also missing. 
Is this correct?

**Comment by sbslee** [comment]
@roman-tremmel,

Thanks for your interest in PyPGx! I'm not sure if I follow your question. Are you talking about the ABCG2 gene? If so, you can find the 1KGP reference haplotype panels in`pypgx-bundle` (see [GRCh37](https://github.com/sbslee/pypgx-bundle/blob/main/1kgp/GRCh37/ABCG2.vcf.gz) and [GRCh38](https://github.com/sbslee/pypgx-bundle/blob/main/1kgp/GRCh38/ABCG2.vcf.gz)).

The reason there are no variant files for GSTT1 and UGT2B17 is because there are no star alleles defined by SNVs/indels for those two genes; they only have star alleles defined by structural variation. If you look at the table in the [Genes](https://pypgx.readthedocs.io/en/latest/genes.html#genes) section you will see that these genes don't have ✅ in the `Variants` column, indicating that they don't have any SNVs/indels (but they have ✅ for the `SV` column).

Please let me know if you have further questions.

**Comment by roman-tremmel** [comment]
Hm, this is strange. I cloned the bundle, but the ABCG2.vcf.gz was missing. Added it manually. 

```
ls $HOME/pypgx-bundle/1kgp/GRCh37
ABCB1.vcf.gz        CYP17A1.vcf.gz.tbi  CYP1B1.vcf.gz       CYP2A6.vcf.gz.tbi   CYP2C9.vcf.gz      CYP2F1.vcf.gz.tbi  CYP2W1.vcf.gz       CYP3A5.vcf.gz.tbi   CYP4B1.vcf.gz      F5.vcf.gz.tbi     IFNL3.vcf.gz      NUDT15.vcf.gz.tbi  SLC15A2.vcf.gz      SLCO1B3.vcf.gz.tbi  TPMT.vcf.gz        UGT2B15.vcf.gz.tbi
ABCB1.vcf.gz.tbi    CYP19A1.vcf.gz      CYP1B1.vcf.gz.tbi   CYP2B6.vcf.gz       CYP2C9.vcf.gz.tbi  CYP2J2.vcf.gz      CYP2W1.vcf.gz.tbi   CYP3A7.vcf.gz       CYP4B1.vcf.gz.tbi  G6PD.vcf.gz       IFNL3.vcf.gz.tbi  POR.vcf.gz         SLC15A2.vcf.gz.tbi  SLCO2B1.vcf.gz      TPMT.vcf.gz.tbi    UGT2B7.vcf.gz
CACNA1S.vcf.gz      CYP19A1.vcf.gz.tbi  CYP26A1.vcf.gz      CYP2B6.vcf.gz.tbi   CYP2D6.vcf.gz      CYP2J2.vcf.gz.tbi  CYP3A4.vcf.gz       CYP3A7.vcf.gz.tbi   CYP4F2.vcf.gz      G6PD.vcf.gz.tbi   NAT1.vcf.gz       POR.vcf.gz.tbi     SLC22A2.vcf.gz      SLCO2B1.vcf.gz.tbi  UGT1A1.vcf.gz      UGT2B7.vcf.gz.tbi
CACNA1S.vcf.gz.tbi  CYP1A1.vcf.gz       CYP26A1.vcf.gz.tbi  CYP2C19.vcf.gz      CYP2D6.vcf.gz.tbi  CYP2R1.vcf.gz      CYP3A4.vcf.gz.tbi   CYP4A11.vcf.gz      CYP4F2.vcf.gz.tbi  GSTM1.vcf.gz      NAT1.vcf.gz.tbi   PTGIS.vcf.gz       SLC22A2.vcf.gz.tbi  SULT1A1.vcf.gz      UGT1A1.vcf.gz.tbi  VKORC1.vcf.gz
CFTR.vcf.gz         CYP1A1.vcf.gz.tbi   CYP2A13.vcf.gz      CYP2C19.vcf.gz.tbi  CYP2E1.vcf.gz      CYP2R1.vcf.gz.tbi  CYP3A43.vcf.gz      CYP4A11.vcf.gz.tbi  DPYD.vcf.gz        GSTM1.vcf.gz.tbi  NAT2.vcf.gz       PTGIS.vcf.gz.tbi   SLCO1B1.vcf.gz      SULT1A1.vcf.gz.tbi  UGT1A4.vcf.gz      VKORC1.vcf.gz.tbi
CFTR.vcf.gz.tbi     CYP1A2.vcf.gz       CYP2A13.vcf.gz.tbi  CYP2C8.vcf.gz       CYP2E1.vcf.gz.tbi  CYP2S1.vcf.gz      CYP3A43.vcf.gz.tbi  CYP4A22.vcf.gz      DPYD.vcf.gz.tbi    GSTP1.vcf.gz      NAT2.vcf.gz.tbi   RYR1.vcf.gz        SLCO1B1.vcf.gz.tbi  TBXAS1.vcf.gz       UGT1A4.vcf.gz.tbi  XPC.vcf.gz
CYP17A1.vcf.gz      CYP1A2.vcf.gz.tbi   CYP2A6.vcf.gz       CYP2C8.vcf.gz.tbi   CYP2F1.vcf.gz      CYP2S1.vcf.gz.tbi  CYP3A5.vcf.gz       CYP4A22.vcf.gz.tbi  F5.vcf.gz          GSTP1.vcf.gz.tbi  NUDT15.vcf.gz     RYR1.vcf.gz.tbi    SLCO1B3.vcf.gz      TBXAS1.vcf.gz.tbi   UGT2B15.vcf.gz     XPC.vcf.gz.tbi
```

**Comment by sbslee** [comment]
@roman-tremmel,

I just confirmed that installing the latest version of `pypgx-bundle` correctly downloads variant files for the ABCG2 gene as well:

```
$ git clone --branch 0.19.0 --depth 1 https://github.com/sbslee/pypgx-bundle
$ ls pypgx-bundle/1kgp/GRCh37 | grep "ABCG2"
ABCG2.vcf.gz
ABCG2.vcf.gz.tbi
```

Can you make sure that you are using the latest version (0.19.0) for both `pypgx` and `pypgx-bundle`? You can check the version of the bundle by:

```
$ cat pypgx-bundle/VERSION 
0.19.0
```

**Comment by roman-tremmel** [comment]
yes, I can confirm that it is included. I figured out that in the manual an older branch version is mentioned. Simply c&p issue ;) 

    git clone --branch 0.12.0 --depth 1 https://github.com/sbslee/pypgx-bundle
