### ISSUE TITLE
Introducing `create-input-vcf` command

### ISSUE THREAD

**Issue by sbslee** [sbslee/pypgx#54]
This new command can be used to create a VCF file (containing SNVs/indels) from BAM files.

Before this command, users were supposed to create a VCF file from BAM files on their own in order to run the [NGS pipeline](https://pypgx.readthedocs.io/en/latest/readme.html#ngs-pipeline). This raises several potential problems:

1. PyPGx results depend on which germline variant caller is used (e.g. GATK4, bcftools, DRAGEN, DeepVariant), which in turn can negatively impact the reproducibility of PyPGx. Even if the same variant caller is used, there is no guarantee that the same version of the tool is used.
2. This assumes that PyPGx users are already familiar with ins and outs of variant calling (e.g. know how to control the balance between sensitivity vs. specificity). PyPGx strongly recommends producing input VCF that contains all possible SNVs/indels to achieve maximum sensitivity because it will only use known variants for genotyping purposes anyways (i.e. variants used to define star alleles). Therefore, PyPGx is actually quite robust against false positives.
3. In the case of genes with structural variation, PyPGx strongly recommends producing input VCF with allelic depth data (i.e. `AD` tag). See [here](https://pypgx.readthedocs.io/en/latest/readme.html#structural-variation-detection) for why. However, the `AD` tag is not something that every variant caller produces by default (it almost always needs to be requested by user). 
4. In the case of WGS data, input VCF file can be quite large so in many cases users are forced to slice the VCF to contain PyPGx target genes only. This task can be tiresome -- users would need to first extract PyPGx target regions (e.g. `pypgx create-regions-bed`) and then actually do the slicing using a software tool. Of course, users could restrict variant calling to PyPGx target regions only from the beginning, but they would still need to extract PyPGx regions first.
5. Often, many of the popular variant callers such as GATK4 are very slow and require a huge amount of computing resources. This is because they all use fancy algorithms for maximizing sensitivity and specificity (e.g. GATK4 uses what's known as "local re-assembly of haplotypes"). However, as illustrated in point 2, PyPGx is less concerned about specificity, so it does not require these highly sophisticated algorithms.

That's why I've introduced the `create-input-vcf` command in `0.14.0-dev`, which calls SNVs/indels from BAM files using the `bcftools` program internally. If you didn't know, `bcftools` is very "classic" in that it uses less sophisticated algorithm (likelihood-based) for calling variants than, say, GATK4 but it's still very reliable and fast. Therefore, by using `bcftools` with maximum sensitivity setting, we can create input VCF that's suitable for PyPGx. 

Even with the help from `bcftools`, one would normally need to construct a variant calling pipeline to create a VCF file, which can be quite complex. Therefore, when developing `pypgx create-input-vcf`, I made sure the command line is as simple as possible with sensible choice of parameters for variant calling:

```
$ pypgx create-input-vcf out.vcf.gz ref.fa bam.list
```

The `out.vcf.gz` file will be already indexed for random access (i.e. `out.vcf.gz.tbi`) and therefore can be directly used with `pypgx run-ngs-pipeline`.

Below is the full help message for the command:

```
$ pypgx create-input-vcf -h
usage: pypgx create-input-vcf [-h] [--assembly TEXT] [--genes TEXT [TEXT ...]]
                              [--exclude] [--dir-path PATH]
                              vcf fasta bams [bams ...]

Call SNVs/indels from BAM files for all target genes.

To save computing resources, this method will call variants only for target
genes whose at least one star allele is defined by SNVs/indels. Therefore,
variants will not be called for target genes that have star alleles defined
only by structural variation (e.g. UGT2B17).

Positional arguments:
  vcf                   Output VCF file. It must have .vcf.gz as suffix.
  fasta                 Reference FASTA file.
  bams                  One or more input BAM files. Alternatively, you can
                        provide a text file (.txt, .tsv, .csv, or .list)
                        containing one BAM file per line.

Optional arguments:
  -h, --help            Show this help message and exit.
  --assembly TEXT       Reference genome assembly (default: 'GRCh37')
                        (choices: 'GRCh37', 'GRCh38').
  --genes TEXT [TEXT ...]
                        List of genes to include.
  --exclude             Exclude specified genes. Ignored when --genes is not
                        used.
  --dir-path PATH       By default, intermediate files (likelihoods.bcf,
                        calls.bcf, and calls.normalized.bcf) will be stored
                        in a temporary directory, which is automatically
                        deleted after creating final VCF. If you provide a
                        directory path, intermediate files will be stored
                        there.
```

I hope this will help standardize the NGS pipeline even further.

Disclaimer: There will be cases where more sophisticated variant callers are preferred, or even suitable, to generate input VCF for PyPGx. For example, if your samples are ancient DNA then you would probably want to use callers like ATLAS to correct for ancient DNA damage. Also, if you've already created input VCF for purposes other than running PyPGx and you want/need to be consistent with the other variant-level analyses you may also just use the same VCF for PyPGx. The bottom line is, if you are going to create your own input VCF, then you need to know what you are doing. Otherwise, it's probably safer to use `pypgx create-input-vcf`.

**Comment by NourMarzouka** [comment]
Does using the create-input-vcf command—or slicing the VCF to the PyPGx BED regions—affect phasing in downstream steps, considering that the number of variants will be reduced compared to using the full chromosome?
