### ISSUE TITLE
can CRAM be used as input?

### ISSUE THREAD

**Issue by brettva** [sbslee/pypgx#72]
Hello,

Thank you for developing pypgx. Can CRAM be used as input in place of BAM?

EDIT: I am also interested in if there are any obvious processing steps that were applied to the CRAMs that I should be on the lookout for when evaluating whether these CRAMS are suitable as input for pypgx.

**Comment by sbslee** [comment]
Hi @brettva,

Yes, CRAM should work just fine in theory, although I haven't had a chance to work with the format as much as BAM to be honest. If you look at the NGS [pipeline](https://pypgx.readthedocs.io/en/latest/readme.html#ngs-pipeline), an alignment file is used to create three input files: 1) VCF, 2) depth of coverage, and 3) summary statistics for control. Note that 1) is based on `bcftools` while the later two are based on `samtools`, both of which support CRAM natively. So my answer is: please give CRAM a try! PyPGx should support CRAM, so if you encounter any problems I can definitely help you solve them. But please just make sure that you are using the latest version for `pypgx` (0.19.0), `pypgx-bundle` (0.19.0), and `fuc` (0.36.0).

**Comment by sbslee** [comment]
Please re-open it if necessary.
