### ISSUE TITLE
CPIC/PharamGKB recommendations

### ISSUE THREAD

**Issue by Bioinf-usr** [sbslee/pypgx#77]
Hi Steven,

Thanks a lot for this great tool.

Do you have any plans in the future to automatically generate CPIC/PharmGKB recommendations based on the predicted phenotyoe from pypgx?

Thanks,

Regards,
Dheeraj.

**Comment by sbslee** [comment]
@dheeraj-bobbili1988,

Thanks for the inquiry!

The short answer is yes/no... What I mean by that is, there is already a function in PyPGx API called `pypgx.get_recommendation` (see [documentation](https://pypgx.readthedocs.io/en/latest/api.html?highlight=recommendation#pypgx.api.core.get_recommendation)):

```
>>> import pypgx
>>> # Codeine, an opiate and prodrug of morphine, is metabolized by CYP2D6
>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Normal Metabolizer')
'Use codeine label recommended age- or weight-specific dosing.'
>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Ultrarapid Metabolizer')
'Avoid codeine use because of potential for serious toxicity. If opioid use is warranted, consider a non-tramadol opioid.'
>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Poor Metabolizer')
'Avoid codeine use because of possibility of diminished analgesia. If opioid use is warranted, consider a non-tramadol opioid.'
>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Indeterminate')
'None'
>>> # It's possible to have an altered recommendation for Normal Metabolizer
>>> pypgx.get_recommendation('tacrolimus', 'CYP3A5', 'Normal Metabolizer')
'Increase starting dose 1.5 to 2 times recommended starting dose. Total starting dose should not exceed 0.3 mg/kg/day. Use therapeutic drug monitoring to guide dose adjustments.'
>>> # Some recommendations are determined by multiple genes (the order doesn't matter)
>>> pypgx.get_recommendation('fluvastatin', 'CYP2C9', 'Normal Metabolizer')
/Users/sbslee/Desktop/pypgx/pypgx/api/core.py:633: UserWarning: Recommendations for fluvastatin are determined by multiple genes (CYP2C9, SLCO1B1); for best results, specify phenotype for each gene
  warnings.warn(message)
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
>>> pypgx.get_recommendation('fluvastatin', 'SLCO1B1', 'Normal Function')
/Users/sbslee/Desktop/pypgx/pypgx/api/core.py:633: UserWarning: Recommendations for fluvastatin are determined by multiple genes (CYP2C9, SLCO1B1); for best results, specify phenotype for each gene
  warnings.warn(message)
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
>>> pypgx.get_recommendation('fluvastatin', 'CYP2C9', 'Normal Metabolizer', 'SLCO1B1', 'Normal Function')
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
>>> pypgx.get_recommendation('fluvastatin', 'SLCO1B1', 'Normal Function', 'CYP2C9', 'Normal Metabolizer')
'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'
```

However, I have not implemented this function into any of the existing automated pipelines (e.g. NGS). This is because it requires a careful design of PGx genotyping report and I'm not an expert at designing such report. I was hoping other people will use `pypgx.get_recommendation` to design such report.

That being said, if you are an expert yourself and are interested in extending PyPGx to automatically output PGx report(s), please let me know. I'd be more than happy to help.

Steven

**Comment by Bioinf-usr** [comment]
Hi Steven,

Thanks for the response. Indeed, I am interested to generate automated reports. Please let me know how can we proceed here. Happy to catch up over a call and explain what is it that I intend to develop.

Thank you,
Regards,
Dheeraj.

From: sbslee ***@***.***>
Date: Wednesday, 21 December 2022 at 05:29
To: sbslee/pypgx ***@***.***>
Cc: Bioinf ***@***.***>, Mention ***@***.***>
Subject: Re: [sbslee/pypgx] CPIC/PharamGKB recommendations (Issue #77)

@dheeraj-bobbili1988<https://github.com/dheeraj-bobbili1988>,

Thanks for the inquiry!

The short answer is yes/no... What I mean by that is, there is already a function in PyPGx API called pypgx.get_recommendation (see documentation<https://pypgx.readthedocs.io/en/latest/api.html?highlight=recommendation#pypgx.api.core.get_recommendation>):

>>> import pypgx

>>> # Codeine, an opiate and prodrug of morphine, is metabolized by CYP2D6

>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Normal Metabolizer')

'Use codeine label recommended age- or weight-specific dosing.'

>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Ultrarapid Metabolizer')

'Avoid codeine use because of potential for serious toxicity. If opioid use is warranted, consider a non-tramadol opioid.'

>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Poor Metabolizer')

'Avoid codeine use because of possibility of diminished analgesia. If opioid use is warranted, consider a non-tramadol opioid.'

>>> pypgx.get_recommendation('codeine', 'CYP2D6', 'Indeterminate')

'None'

>>> # It's possible to have an altered recommendation for Normal Metabolizer

>>> pypgx.get_recommendation('tacrolimus', 'CYP3A5', 'Normal Metabolizer')

'Increase starting dose 1.5 to 2 times recommended starting dose. Total starting dose should not exceed 0.3 mg/kg/day. Use therapeutic drug monitoring to guide dose adjustments.'

>>> # Some recommendations are determined by multiple genes (the order doesn't matter)

>>> pypgx.get_recommendation('fluvastatin', 'CYP2C9', 'Normal Metabolizer')

/Users/sbslee/Desktop/pypgx/pypgx/api/core.py:633: UserWarning: Recommendations for fluvastatin are determined by multiple genes (CYP2C9, SLCO1B1); for best results, specify phenotype for each gene

  warnings.warn(message)

'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'

>>> pypgx.get_recommendation('fluvastatin', 'SLCO1B1', 'Normal Function')

/Users/sbslee/Desktop/pypgx/pypgx/api/core.py:633: UserWarning: Recommendations for fluvastatin are determined by multiple genes (CYP2C9, SLCO1B1); for best results, specify phenotype for each gene

  warnings.warn(message)

'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'

>>> pypgx.get_recommendation('fluvastatin', 'CYP2C9', 'Normal Metabolizer', 'SLCO1B1', 'Normal Function')

'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'

>>> pypgx.get_recommendation('fluvastatin', 'SLCO1B1', 'Normal Function', 'CYP2C9', 'Normal Metabolizer')

'Prescribe desired starting dose and adjust doses of fluvastatin based on disease-specific guidelines.'

However, I have not implemented this function into any of the existing automated pipelines (e.g. NGS). This is because it requires a careful design of PGx genotyping report and I'm not an expert at designing such report. I was hoping other people will use pypgx.get_recommendation to design such report.

That being said, if you are an expert yourself and are interested in extending PyPGx to automatically output PGx report(s), please let me know. I'd be more than happy to help.

Steven

**Comment by sbslee** [comment]
@Bioinf-usr

Hi Dheeraj, happy to have a call with you via Zoom, etc. I'm not sure which time zone you are in, but I currently live in South Korea and I can meet you today. Please send an invite to sbstevenlee@gmail.com.

Steven

**Comment by sbslee** [comment]
Also closing this. Please feel free to re-open it if needed.
