### ISSUE TITLE
If the input sample name consists of only numbers, "ValueError: Different sample sets found" is happened when running compute-copy-number alteration.

### ISSUE THREAD

**Issue by leefall** [sbslee/pypgx#78]
If the input sample name consists of only numbers, the "read_depth.data.samples" contains the sample name as a string type. 

However the "control_statistics.data.index" contains the sample name as an integer data type.

It caused the 'ValueError('Different sample sets found')' and KeyError: "None of [Index(['1642'], dtype='object')] are in the [index]" during running compute-copy-number.

Is there any solution except attaching some string to the sample name?

Best regards,

**Comment by sbslee** [comment]
@leefall,

Thanks for reporting the issue! I was able to reproduce the error myself. PyPGx should be able to handle sample names that consist of only numbers.

That said, I made a fix to the `0.20.0-dev` branch. In my testing, it works fine now. I simply added a line of code that explicitly converts the index as string. Please give this new version a try by local installation (see [how](https://pypgx.readthedocs.io/en/latest/readme.html#installation)) and let me know if it works for you as well.

I have been planning to release the official version of `0.20.0` so if the fix works for you, I will upload the new version to `pip` and `conda` soon.

Thanks!

**Comment by leefall** [comment]
Thanks for your quick and kind response.
I will try after updating the version.

**Comment by leefall** [comment]
It worked!!
I appreciate your fix.

Sincerely,

**Comment by sbslee** [comment]
@leefall, I just uploaded the official version of `0.20.0` to `pip` and `conda`. Enjoy!
