### ISSUE TITLE
Interpreting Outputs

### ISSUE THREAD

**Issue by anh151** [sbslee/pypgx#83]
Hello,
I'm trying to understand how to interpret some of the Indeterminate outputs from pypgx for CYP2D6 GRCh38. It is not clear to me why an Indeterminate call is made. Few examples below. Explaining these might help my understand the rest.

```
Unnamed: 0 | Genotype | Phenotype | Haplotype1 | Haplotype2 | AlternativePhase | VariantData | CNV
123 | Indeterminate | Indeterminate | *17;*2; | *29;*2; | ; | *29:22-42129132-C-T,22-42127608-C-T:0.675,0.631;*17:22-42129770-G-A:0.294;*2:22-42126611-C-G,22-42127941-G-A:1.0,1.0; | Tandem2A
1234 | Indeterminate | Indeterminate | *2; | *2; | ; | *2:22-42127941-G-A,22-42126611-C-G:1.0,1.0; | Tandem3
12345 | Indeterminate | Indeterminate | *28;*2; | *2; | ; | *28:22-42129087-G-C,22-42130773-C-T:0.525,0.589;*2:22-42126611-C-G,22-42127941-G-A:1.0,1.0; | Tandem1A
123456 | Indeterminate | Indeterminate | *2; | *4;*10; | *65; | *4:22-42128945-C-T:0.483;*10:22-42130692-G-A,22-42126611-C-G:0.448,1.0;*65:22-42130692-G-A,22-42127941-G-A,22-42126611-C-G:0.448,0.457,1.0;*2:22-42127941-G-A,22-42126611-C-G:0.457,1.0; | WholeMultip1
1234567 | Indeterminate | Indeterminate | *2; | *17;*2; | ; | *17:22-42129770-G-A:0.527;*2:22-42127941-G-A,22-42126611-C-G:1.0,1.0; | Tandem2B
```

**Comment by sbslee** [comment]
@anh151,

Good question! If you look more closely at these samlpes, they all have a structural variant call (e.g. `Tandem3`) in the `CNV` column. In these particular cases, PyPGx did not know how to interpet these calls in the context of candidate star alleles (i.e. the `Haplotype1` and `Haplotype2` columns) and thus produced `Indeterminate` calls. Please let me know if you have additional questions.

Best regards,
Steven

**Comment by anh151** [comment]
@sbslee 
Let's take for example the second sample. It looks like pypgx detected a *2 allele on each chromosome. But then also a structural variant somewhere. Is a *2+strucutral variant allele tandem not possible? Or is the structural variant that doesn't match any known definitions?

-Andrew

**Comment by sbslee** [comment]
@anh151,

The latter is what I menat -- i.e. that particular combination does not match any known star allele definition. If you are interested in learning more about alleles defined by SV, please see PyPGx's [allele table](https://github.com/sbslee/pypgx/blob/master/pypgx/api/data/allele-table.csv) and also the list of example SV alleles in the [Genes page](https://pypgx.readthedocs.io/en/latest/genes.html#) (see [CYP2D6](https://pypgx.readthedocs.io/en/latest/genes.html#sv-summary-for-cyp2d6) page as an example).

**Comment by anh151** [comment]
Great! That helps a lot. Thanks.

-Andrew
