### ISSUE TITLE
Recommendations for comparing pypgx calls to commercial tests?

### ISSUE THREAD

**Issue by brettva** [sbslee/pypgx#86]
Hi Steven,

I have some folks genotyped for DPYD via a commercial test that evaluates *2A, *7, *8, *10, *13, HapB3 (and reports *1 when none of these variants are identified)

These folks are also genotyped by array  on GRCh38 and I was planning to compare the concordance between pypgx on array and the commercial test. 

I noticed the GRCh38Default for DPYD is Reference, so I am running into cases where commercial test calls things like *1/HapB3 and pypgx calls Reference/HapB3. 

I am thinking these would be concordant diplotypes  if Reference is the allele provided when none of the named alleles are detected by pypgx (similar to *1 for the commercial test), but thought I would get your take on it 

Please let me know what you think , thanks

**Comment by sbslee** [comment]
@brettva,

Good question! The short answer is, yes, the `Reference` allele is the same as `*1` for DPYD. Therefore, `*1/HapB3` and `Reference/HapB3` are two identical diplotype calls.

My understanding is that the PGx community is no longer using the star allele nomenclature for DPYD. See PharmVar's [DPYD page](https://www.pharmvar.org/gene/DPYD) for example -- they've put star allele names as legacy label.

Before I finish, let me introduce some resources that could be potentially useful to you and future readers:

- PyPGx's [allele table](https://github.com/sbslee/pypgx/blob/master/pypgx/api/data/allele-table.csv) - users can find allele definitions
- PyPGx' [gene table](https://github.com/sbslee/pypgx/blob/master/pypgx/api/data/gene-table.csv) - users can find which allele is the reference allele for each target gene
- FAQ on [Reference vs. default star alleles
](https://pypgx.readthedocs.io/en/latest/faq.html#reference-vs-default-star-alleles)

Let me know if you have further questions.

**Comment by brettva** [comment]
@sbslee sorry to bring this up again, but we are also looking at concordance between pypgx and a gold standard test for UGT2B15. 

The gold standard test calls *1 default, my understanding is that pypgx calls *2 default.

How would you recommend evaluating concordance when the gold standard is calling *1 and pypgx is calling *2 and vice versa (we are seeing both).

Any advice is greatly appreciated

**Comment by sbslee** [comment]
@brettva,

According to the UGT2B15 haplotype [nomenclature](https://www.pharmacogenomics.pha.ulaval.ca/wp-content/uploads/2015/04/HAP-UGT2B15.htm), `*2` is defined by `c.253G>T` whose rsID is [rs1902023](https://www.ncbi.nlm.nih.gov/snp/rs1902023#variant_details). However, if you look at the rsID closely in dbSNP you will see that it actually says `c.253T>G` (`G>T` vs. `T>G`) for both GRCh37 and GRCh38. 

This means, both GRCh37 and GRCh38 have the `*2` sequence and therefore if the sample has no observed variants in VCF, it should get assigned `*2/*2`. If the sample is homozygous for `4-69964338-T-C` (GRCh37) or `4-69098620-T-C` (GRCh38), then the sample should get assigned `*1/*1`.

That being said, if the "gold standard test" is calling `*1` while PyPGx is calling `*2`, then it's a discordant call unlike the case of DYPD above. As for why this discordancy happened, I will need more information.

Which genotyping method does this test use (sequencing or SNP array)?

Also, what's the concordance rate for `*1` vs. `*2`? If it's high, then it could be a systematic difference in how the two platofrms are defining `*2`. If it's low, then it could be related to the sensitivity of rs1902023 detection.

**Comment by brettva** [comment]
Thanks @sbslee, I have to admit I realized a mistake in my analysis based on your response, so I think the discordance between `*1` and `*2` is not issue. I am embarrassed and apologize for this. 

I have a related question though. 

For context we are supplying TOPMed imputed sites to pypgx to infer star alleles in our biobank, which we are then comparing to "gold standard" commercial calls from [genesight](https://genesight.com/wp-content/uploads/2021/05/GeneSight.Psychotropic.Report.pdf) which measures `*2 (NM_001076.3:c.253G>T)`  or iiuc `4-68670366-C-A` and `*1` is reported by default when `*2` is not detected.

Most calls match perfectly between methods, but I am seeing a handful of calls that are the following

genesight  -> `*1 (default)/*2 (4-68670366-C-A)`
pypgx -> `*4 (4-68670366-A-C,4-68647129-T-G)/*2 (default)`

I am thinking that these would be concordant following some documentation to describe downgrading `*4` from pypgx to `*1` due to `*1` and `*4` both sharing `4-68670366-A-C` but genesight lacking coverage to interrogate `4-68647129-T-G`

Does that seem reasonable? 

Thanks for all your input on these comparisons so far

**Comment by sbslee** [comment]
@brettva,

The report from GeneSight indicates that they have only tested `UGT2B15 *2 (NM_001076.3:c.253G>T)`. Therefore, I agree that it would be fair to call `*1/*2` from GeneSight vs. `*2/*4` from PyPGx as concordant because the difference stemmed from testing coverage, not detection sensitivity or interpretation. Basically, if PyPGx didn't have `*4` in its allele table, it would have produced `*1/*2` as well.

P.S. This is one of the reasons why it's tricky to compare PGx platforms :)

**Comment by brettva** [comment]
@sbslee Thanks I really appreciate the input
