### ISSUE TITLE
Additional Pharmacogenes

### ISSUE THREAD

**Issue by labdyn** [sbslee/pypgx#95]
Is there a way to add more pharmacogenes to this script if needed? Or is there a scientific limitation to what the script is able interpret?

**Comment by sbslee** [comment]
Hi @labdyn,

You can certainly add new genes to PyPGx. See #39 as an example. Adding a new gene is mostly just updating the existing tables (e.g. `allele-table.csv`). Which gene(s) are you looking at? I'd be more than happy to assist you in this regard. Let me know.

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
