### ISSUE TITLE
importing external CNV calls

### ISSUE THREAD

**Issue by pjgreer** [sbslee/pypgx#98]
Per issue #56 last year, has there ever been any traction made in importing CNV calls from external programs? 

I am working with some affy phramacoscan data that includes CNV calling within the VCF file via their power tools and would like to test concordance with pypgx.

**Comment by sbslee** [comment]
@pjgreer,

Thanks for the question. There hasn't been much progress regarding the import of CNV calls from external programs, but that doesn't mean it can't be done! I'd be more than happy to assist you in integrating CNV calls from PharmacoScan into PyPGx. Can you share an example VCF file along with its CNV calls so I can take a look?

BTW, doesn't PharmacoScan already provide a software tool for calling star alleles including those with CNV? I assume you are talking about the microarray solution from Thermo Fisher (Affymetrix). I'm curious to learn more about the use case for PyPGx in this context.

**Comment by sbslee** [comment]
Closed due to inactivity. Please feel free to re-open it if necessary.
